#!/bin/bash

if [ "$1" == "bootstrap" ]
    then 
        ./scripts/bootstrap.sh
fi

if [ "$1" == "start" ]
    then
        ./scripts/start.sh
fi

if [ "$1" == "restart" ]
    then
        ./scripts/restart.sh
fi

if [ "$1" == "stop" ]
    then 
        ./scripts/stop.sh
fi

if [ "$1" == "version" ]
    then 
        ./scripts/version.sh $*
fi

if [ "$1" == "publish" ]
    then 
        ./scripts/publish.sh $*
fi

if [ "$1" == "yarn" ]
    then 
        ./scripts/app.sh $*
fi
